### PR TITLE
fix(Badge): adding width styles

### PR DESCRIPTION
**Pull request by slhay28**

### CODE REVIEW

**Comment by chiefcll** [comment]
Should badge have a width or autosize based on the text?

**Comment by chiefcll** [comment]
I think this is currently working in dev with the latest:
image

**Comment by chiefcll** [comment]
I don't think the text is working in the deployed version...

**Comment by anthony9187** [comment]
> I don't think the text is working in the deployed version...

yep, seems to be an issue loading font assets

Screen Shot 2023-12-22 at 11 12 20 AM

**Comment by anthony9187** [comment]
closing this as it's an issue with the static site deployment, not the component

**Pull request closed without merging**
