### PR TITLE
Migrate solid

### PR DESCRIPTION
**Pull request by chiefcll**
Rewrite all the imports to new solid home.

### CODE REVIEW

**Comment by slhay28** [comment]
all stories are throwing this error
`The requested module '/node_modules/.cache/storybook/default/sb-vite/deps/@lightningtv_solid.js?v=1a9e9319' does not provide an export named 'View'`.

Is View located somewhere else now?

**Comment by slhay28** [comment]
yup, reran `pnpm i` just now also and got same error

**Comment by anthony9187** [comment]
seeing the same error, I'll try and dig in a bit

**Comment by anthony9187** [comment]
hardcoding the version to 0.0.13 resolved that issue, now I'm seeing some font issues in storybook:

```
chunk-HLAU6QKI.js?v=79fd5268:55 Uncaught Error: Could not resolve font face for normal 500 normal 25px Arial
    at assertTruthy (chunk-HLAU6QKI.js?v=79fd5268:55:11)
    at CanvasTextRenderer.updateState (chunk-HLAU6QKI.js?v=79fd5268:2104:7)
    at chunk-HLAU6QKI.js?v=79fd5268:1073:12
```

anything that renders text seems to be effected

**Comment by slhay28** [comment]
looks good!

**Review by slhay28 — APPROVED** [review]

**Review by anthony9187 — APPROVED** [review]

**Pull request merged**
